In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
import os
os.chdir('/gdrive/MyDrive/Sınıflandırma')
!ls

 Logistic_Reg.ipynb   veri.csv	'veriler.csv '


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
veriler = pd.read_csv('veri.csv')
print(veriler)

   ulke  boy  kilo   yas cinsiyet
0    tr  180    90  30.0        e
1    tr  190    80  25.0        e
2    tr  175    90  35.0        e
3    tr  177    60  22.0        k
4    us  185   105  33.0        e
5    us  165    55  27.0        k
6    us  155    50  44.0        k
7    us  160    58  39.0        k
8    us  162    59  41.0        k
9    us  167    62  55.0        k
10   fr  174    70  47.0        e
11   fr  193    90  23.0        e
12   fr  187    80  27.0        e
13   fr  183    88  28.0        e
14   fr  159    40  29.0        k
15   fr  164    66  32.0        k
16   fr  166    56  42.0        k


In [ ]:
from sklearn.model_selection import train_test_split#test size 0,33 yani %33 ünü test etcez  ve%67 eğitcez

#Boy, kilo ve  yaş  ile cinsiyet tahmini yapması isteniyor.
x=veriler.iloc[:,1:4].values #girdi olark verdiklerimiz(boy,kilo,yaş) bağımsız değişkenler
y=veriler.iloc[:,4:].values#çıktı olarak bu yani cinsiyet

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)
#x ve y sıralı olamlı girdi, çıktı diye
print(x_train)#eğitim seti
print("\n\n\n")
print(x_test)
print("\n\n\n")
print(y_train)
print("\n\n\n")
print(y_test)

[[175.  90.  35.]
 [159.  40.  29.]
 [174.  70.  47.]
 [160.  58.  39.]
 [166.  56.  42.]
 [193.  90.  23.]
 [177.  60.  22.]
 [180.  90.  30.]
 [165.  55.  27.]
 [164.  66.  32.]
 [187.  80.  27.]]




[[190.  80.  25.]
 [155.  50.  44.]
 [162.  59.  41.]
 [167.  62.  55.]
 [183.  88.  28.]
 [185. 105.  33.]]




[['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['e']]




[['e']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

Logistic Reg. Model

In [ ]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression(random_state=0)
logr.fit(X_train, y_train) #eğitim x den ye yi öğreniyor.
y_pred=logr.predict(X_test) #eğitime göre tahmin ediyor X test e sokuyor
print(y_pred)
print(y_test)

['e' 'k' 'k' 'k' 'e' 'e']
[['e']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[3 0]
 [0 3]]
